# Generated by Django 3.0 on 2023-01-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_de_recursos_humanosModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comunicacion_interna', models.TextField()),
                ('Cultura_organizacional', models.CharField(max_length=150)),
                ('Reclutamiento_y_seleccion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Area_de_recursos_humanosModels',
            },
        ),
        migrations.CreateModel(
            name='bodegaModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulos', models.CharField(max_length=100)),
                ('separacion_de_productos', models.CharField(max_length=100)),
                ('anaqueles_y_cajas', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bodegaModels',
            },
        ),
        migrations.CreateModel(
            name='cant_ropasModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Camisetas', models.IntegerField()),
                ('Pantalonetas', models.IntegerField()),
                ('Boxers', models.IntegerField()),
                ('Medias', models.IntegerField()),
                ('Pantalones', models.IntegerField()),
                ('Buzos', models.IntegerField()),
            ],
            options={
                'db_table': 'cant_ropassModels',
            },
        ),
        migrations.CreateModel(
            name='CompraModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('ingreso', models.IntegerField()),
                ('persona', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CompraModels',
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono_movil', models.CharField(max_length=11)),
                ('telefono_fijo', models.CharField(max_length=11)),
                ('mail', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='i_proyecto')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='DepartamentosModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pisos', models.TextField()),
                ('Muros', models.TextField()),
                ('recubrimientos_y_elementos_decorativos', models.TextField()),
                ('Griferia', models.CharField(max_length=150)),
                ('accesorios_y_muebles_para_bano', models.CharField(max_length=150)),
                ('Materiales_para_construccion', models.TextField()),
            ],
            options={
                'db_table': 'DepartamentosModels',
            },
        ),
        migrations.CreateModel(
            name='EgresoModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'EgresoModels',
            },
        ),
        migrations.CreateModel(
            name='pedidoModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.IntegerField()),
                ('fecha_entrada_pedido', models.DateTimeField(auto_now_add=True)),
                ('espera_de_pedido', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pedidoModels',
            },
        ),
        migrations.CreateModel(
            name='Princip_clientesModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathon', models.CharField(max_length=150)),
                ('adidas', models.CharField(max_length=150)),
                ('shoesalvarito', models.CharField(max_length=150)),
                ('nike', models.CharField(max_length=150)),
                ('puma', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Princip_clientosModels',
            },
        ),
        migrations.CreateModel(
            name='trabajadoresModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_trabajadores', models.IntegerField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('horas_extras', models.DateTimeField(auto_now_add=True)),
                ('remuneraciones', models.DecimalField(decimal_places=2, max_digits=5)),
                ('decimos', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'TrabajadoresModels',
            },
        ),
    ]
